Repository coopiteasy/addons, pull requests merged in 2022-06, with the labels that each got.

#238 [FIX] 304 status response
  document_hosting/controllers/main.py
Labels: needs review

#239 [ADD] website_sale_product_weight
  setup/website_sale_product_weight/odoo/addons/website_sale_product_weight
  setup/website_sale_product_weight/setup.py
  website_sale_product_weight/__init__.py
  website_sale_product_weight/__manifest__.py
  website_sale_product_weight/models/__init__.py
  website_sale_product_weight/models/product_template.py
  website_sale_product_weight/readme/CONTRIBUTORS.rst
  website_sale_product_weight/readme/CREDITS.rst
  website_sale_product_weight/readme/DESCRIPTION.rst
  website_sale_product_weight/static/src/js/product_configurator_mixin.js
  website_sale_product_weight/views/assets.xml
  website_sale_product_weight/views/templates.xml
Labels: needs review, bot is merging ⏳

#246 [FIX] pos_customer_wallet: Partner form should not break for users wi…
  pos_customer_wallet/models/res_partner.py
Labels: needs review, bot is merging ⏳

#235 [ADD] account_customer_wallet: Search on customer_wallet_balance
  account_customer_wallet/models/res_partner.py
  account_customer_wallet/readme/newsfragments/235.feature.rst
  account_customer_wallet/tests/__init__.py
  account_customer_wallet/tests/test_search.py
  account_customer_wallet/views/res_partner_views.xml
Labels: bot is merging ⏳

#242 [ADD] mail_activity_filter_internal_user
  mail_activity_filter_internal_user/__init__.py
  mail_activity_filter_internal_user/__manifest__.py
  mail_activity_filter_internal_user/models/__init__.py
  mail_activity_filter_internal_user/models/mail_activity.py
  mail_activity_filter_internal_user/readme/CONTRIBUTORS.rst
  mail_activity_filter_internal_user/readme/DESCRIPTION.rst
  mail_activity_filter_internal_user/readme/newsfragments/1.feature.rst
  mail_activity_filter_internal_user/views/mail_activity.xml
  setup/mail_activity_filter_internal_user/odoo/addons/mail_activity_filter_internal_user
  setup/mail_activity_filter_internal_user/setup.py
Labels: needs review, bot is merging ⏳
